---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
    # name, does not have to be versioned, versionSelection.constraints below will handle
    name: "local-user-authenticator-package-install"
    namespace: "local-user-authenticator-install-ns"
spec:
  serviceAccountName: "pinniped-package-rbac-local-user-authenticator-sa-superadmin-dangerous"
  packageRef:
    refName: "local-user-authenticator.pinniped.dev"
    versionSelection:
      constraints: "0.0.0-7E26B8EF-A4D6-4020-83E8-EAF8F3D1533F"
  values:
  - secretRef:
      name: "local-user-authenticator-package-install-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: "local-user-authenticator-package-install-secret"
  namespace: "local-user-authenticator-install-ns"
stringData:
  values.yml: |
    ---
    image_repo: kind-registry.local:5000/test/build
    image_tag: 0.0.0-7E26B8EF-A4D6-4020-83E8-EAF8F3D1533F
