---
apiVersion: v1
kind: Namespace
metadata:
  name: "local-user-authenticator-install-ns"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "pinniped-package-rbac-local-user-authenticator-sa-superadmin-dangerous"
  namespace: "local-user-authenticator-install-ns"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "pinniped-package-rbac-local-user-authenticator-role-superadmin-dangerous"
  namespace: "local-user-authenticator-install-ns"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "pinniped-package-rbac-local-user-authenticator-role-binding-superadmin-dangerous"
subjects:
- kind: ServiceAccount
  name: "pinniped-package-rbac-local-user-authenticator-sa-superadmin-dangerous"
  namespace: "local-user-authenticator-install-ns"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "pinniped-package-rbac-local-user-authenticator-role-superadmin-dangerous"

