---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
    # name, does not have to be versioned, versionSelection.constraints below will handle
    name: "supervisor-package-install"
    namespace: "supervisor-install-ns"
spec:
  serviceAccountName: "pinniped-package-rbac-supervisor-sa-superadmin-dangerous"
  packageRef:
    refName: "supervisor.pinniped.dev"
    versionSelection:
      constraints: "0.0.0-EEE84AC0-DE44-425C-8785-4C6DD92307F7"
  values:
  - secretRef:
      name: "supervisor-package-install-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: "supervisor-package-install-secret"
  namespace: "supervisor-install-ns"
stringData:
  values.yml: |
    ---
    app_name: pinniped-supervisor
    namespace: supervisor
    api_group_suffix: pinniped.dev
    image_repo: kind-registry.local:5000/test/build
    image_tag: 0.0.0-EEE84AC0-DE44-425C-8785-4C6DD92307F7
    log_level: debug

    service_https_nodeport_port: 443
    service_https_nodeport_nodeport: 31243
    service_https_clusterip_port: 443
