#@ load("@ytt:data", "data")  # for reading data values (generated via ytt's data-values-schema-inspect mode).
#@ load("@ytt:yaml", "yaml")  # for dynamically decoding the output of ytt's data-values-schema-inspect
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "concierge.pinniped.dev." + data.values.package_version
  namespace: #@ data.values.namespace
spec:
  refName: concierge.pinniped.dev
  version: #@ data.values.package_version
  releaseNotes: |
        Initial release of the pinniped concierge package, TODO: AUTOMATE THIS??
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  template:
    spec:
      fetch:
      - imgpkgBundle:
          #! image: #@ data.values.package_image_repo + "/packages/:" + data.values.package_version
          image: #@ data.values.package_image_repo
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}
