---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
    # name, does not have to be versioned, versionSelection.constraints below will handle
    name: concierge-install
    namespace: concierge-install-ns
spec:
  serviceAccountName: "pinniped-package-rbac-concierge-sa-superadmin-dangerous"
  packageRef:
    refName: "concierge.pinniped.dev"
    versionSelection:
      constraints: "0.25.0"
  values:
  - secretRef:
      name: "concierge-package-install-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: "concierge-package-install-secret"
  namespace: concierge-install-ns
stringData:
  values.yml: |
    ---
    namespace: "concierge"
    app_name: "concierge"    # this affects services and things, needs to be just the resource name to match hack scripts
    replicas: 1                     # keep logs testing easy
