// +build !ignore_autogenerated

/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	placeholder "github.com/suzerain-io/placeholder-name/kubernetes/1.19/api/apis/placeholder"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CredentialRequest)(nil), (*placeholder.CredentialRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CredentialRequest_To_placeholder_CredentialRequest(a.(*CredentialRequest), b.(*placeholder.CredentialRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*placeholder.CredentialRequest)(nil), (*CredentialRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_placeholder_CredentialRequest_To_v1alpha1_CredentialRequest(a.(*placeholder.CredentialRequest), b.(*CredentialRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CredentialRequestCredential)(nil), (*placeholder.CredentialRequestCredential)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CredentialRequestCredential_To_placeholder_CredentialRequestCredential(a.(*CredentialRequestCredential), b.(*placeholder.CredentialRequestCredential), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*placeholder.CredentialRequestCredential)(nil), (*CredentialRequestCredential)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_placeholder_CredentialRequestCredential_To_v1alpha1_CredentialRequestCredential(a.(*placeholder.CredentialRequestCredential), b.(*CredentialRequestCredential), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CredentialRequestList)(nil), (*placeholder.CredentialRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CredentialRequestList_To_placeholder_CredentialRequestList(a.(*CredentialRequestList), b.(*placeholder.CredentialRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*placeholder.CredentialRequestList)(nil), (*CredentialRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_placeholder_CredentialRequestList_To_v1alpha1_CredentialRequestList(a.(*placeholder.CredentialRequestList), b.(*CredentialRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CredentialRequestSpec)(nil), (*placeholder.CredentialRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CredentialRequestSpec_To_placeholder_CredentialRequestSpec(a.(*CredentialRequestSpec), b.(*placeholder.CredentialRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*placeholder.CredentialRequestSpec)(nil), (*CredentialRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_placeholder_CredentialRequestSpec_To_v1alpha1_CredentialRequestSpec(a.(*placeholder.CredentialRequestSpec), b.(*CredentialRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CredentialRequestStatus)(nil), (*placeholder.CredentialRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CredentialRequestStatus_To_placeholder_CredentialRequestStatus(a.(*CredentialRequestStatus), b.(*placeholder.CredentialRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*placeholder.CredentialRequestStatus)(nil), (*CredentialRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_placeholder_CredentialRequestStatus_To_v1alpha1_CredentialRequestStatus(a.(*placeholder.CredentialRequestStatus), b.(*CredentialRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CredentialRequestTokenCredential)(nil), (*placeholder.CredentialRequestTokenCredential)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CredentialRequestTokenCredential_To_placeholder_CredentialRequestTokenCredential(a.(*CredentialRequestTokenCredential), b.(*placeholder.CredentialRequestTokenCredential), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*placeholder.CredentialRequestTokenCredential)(nil), (*CredentialRequestTokenCredential)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_placeholder_CredentialRequestTokenCredential_To_v1alpha1_CredentialRequestTokenCredential(a.(*placeholder.CredentialRequestTokenCredential), b.(*CredentialRequestTokenCredential), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CredentialRequest_To_placeholder_CredentialRequest(in *CredentialRequest, out *placeholder.CredentialRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CredentialRequestSpec_To_placeholder_CredentialRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CredentialRequestStatus_To_placeholder_CredentialRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CredentialRequest_To_placeholder_CredentialRequest is an autogenerated conversion function.
func Convert_v1alpha1_CredentialRequest_To_placeholder_CredentialRequest(in *CredentialRequest, out *placeholder.CredentialRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_CredentialRequest_To_placeholder_CredentialRequest(in, out, s)
}

func autoConvert_placeholder_CredentialRequest_To_v1alpha1_CredentialRequest(in *placeholder.CredentialRequest, out *CredentialRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_placeholder_CredentialRequestSpec_To_v1alpha1_CredentialRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_placeholder_CredentialRequestStatus_To_v1alpha1_CredentialRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_placeholder_CredentialRequest_To_v1alpha1_CredentialRequest is an autogenerated conversion function.
func Convert_placeholder_CredentialRequest_To_v1alpha1_CredentialRequest(in *placeholder.CredentialRequest, out *CredentialRequest, s conversion.Scope) error {
	return autoConvert_placeholder_CredentialRequest_To_v1alpha1_CredentialRequest(in, out, s)
}

func autoConvert_v1alpha1_CredentialRequestCredential_To_placeholder_CredentialRequestCredential(in *CredentialRequestCredential, out *placeholder.CredentialRequestCredential, s conversion.Scope) error {
	out.ExpirationTimestamp = in.ExpirationTimestamp
	out.Token = in.Token
	out.ClientCertificateData = in.ClientCertificateData
	out.ClientKeyData = in.ClientKeyData
	return nil
}

// Convert_v1alpha1_CredentialRequestCredential_To_placeholder_CredentialRequestCredential is an autogenerated conversion function.
func Convert_v1alpha1_CredentialRequestCredential_To_placeholder_CredentialRequestCredential(in *CredentialRequestCredential, out *placeholder.CredentialRequestCredential, s conversion.Scope) error {
	return autoConvert_v1alpha1_CredentialRequestCredential_To_placeholder_CredentialRequestCredential(in, out, s)
}

func autoConvert_placeholder_CredentialRequestCredential_To_v1alpha1_CredentialRequestCredential(in *placeholder.CredentialRequestCredential, out *CredentialRequestCredential, s conversion.Scope) error {
	out.ExpirationTimestamp = in.ExpirationTimestamp
	out.Token = in.Token
	out.ClientCertificateData = in.ClientCertificateData
	out.ClientKeyData = in.ClientKeyData
	return nil
}

// Convert_placeholder_CredentialRequestCredential_To_v1alpha1_CredentialRequestCredential is an autogenerated conversion function.
func Convert_placeholder_CredentialRequestCredential_To_v1alpha1_CredentialRequestCredential(in *placeholder.CredentialRequestCredential, out *CredentialRequestCredential, s conversion.Scope) error {
	return autoConvert_placeholder_CredentialRequestCredential_To_v1alpha1_CredentialRequestCredential(in, out, s)
}

func autoConvert_v1alpha1_CredentialRequestList_To_placeholder_CredentialRequestList(in *CredentialRequestList, out *placeholder.CredentialRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]placeholder.CredentialRequest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_CredentialRequestList_To_placeholder_CredentialRequestList is an autogenerated conversion function.
func Convert_v1alpha1_CredentialRequestList_To_placeholder_CredentialRequestList(in *CredentialRequestList, out *placeholder.CredentialRequestList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CredentialRequestList_To_placeholder_CredentialRequestList(in, out, s)
}

func autoConvert_placeholder_CredentialRequestList_To_v1alpha1_CredentialRequestList(in *placeholder.CredentialRequestList, out *CredentialRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CredentialRequest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_placeholder_CredentialRequestList_To_v1alpha1_CredentialRequestList is an autogenerated conversion function.
func Convert_placeholder_CredentialRequestList_To_v1alpha1_CredentialRequestList(in *placeholder.CredentialRequestList, out *CredentialRequestList, s conversion.Scope) error {
	return autoConvert_placeholder_CredentialRequestList_To_v1alpha1_CredentialRequestList(in, out, s)
}

func autoConvert_v1alpha1_CredentialRequestSpec_To_placeholder_CredentialRequestSpec(in *CredentialRequestSpec, out *placeholder.CredentialRequestSpec, s conversion.Scope) error {
	out.Type = placeholder.CredentialType(in.Type)
	out.Token = (*placeholder.CredentialRequestTokenCredential)(unsafe.Pointer(in.Token))
	return nil
}

// Convert_v1alpha1_CredentialRequestSpec_To_placeholder_CredentialRequestSpec is an autogenerated conversion function.
func Convert_v1alpha1_CredentialRequestSpec_To_placeholder_CredentialRequestSpec(in *CredentialRequestSpec, out *placeholder.CredentialRequestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CredentialRequestSpec_To_placeholder_CredentialRequestSpec(in, out, s)
}

func autoConvert_placeholder_CredentialRequestSpec_To_v1alpha1_CredentialRequestSpec(in *placeholder.CredentialRequestSpec, out *CredentialRequestSpec, s conversion.Scope) error {
	out.Type = CredentialType(in.Type)
	out.Token = (*CredentialRequestTokenCredential)(unsafe.Pointer(in.Token))
	return nil
}

// Convert_placeholder_CredentialRequestSpec_To_v1alpha1_CredentialRequestSpec is an autogenerated conversion function.
func Convert_placeholder_CredentialRequestSpec_To_v1alpha1_CredentialRequestSpec(in *placeholder.CredentialRequestSpec, out *CredentialRequestSpec, s conversion.Scope) error {
	return autoConvert_placeholder_CredentialRequestSpec_To_v1alpha1_CredentialRequestSpec(in, out, s)
}

func autoConvert_v1alpha1_CredentialRequestStatus_To_placeholder_CredentialRequestStatus(in *CredentialRequestStatus, out *placeholder.CredentialRequestStatus, s conversion.Scope) error {
	out.Credential = (*placeholder.CredentialRequestCredential)(unsafe.Pointer(in.Credential))
	out.Message = (*string)(unsafe.Pointer(in.Message))
	return nil
}

// Convert_v1alpha1_CredentialRequestStatus_To_placeholder_CredentialRequestStatus is an autogenerated conversion function.
func Convert_v1alpha1_CredentialRequestStatus_To_placeholder_CredentialRequestStatus(in *CredentialRequestStatus, out *placeholder.CredentialRequestStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CredentialRequestStatus_To_placeholder_CredentialRequestStatus(in, out, s)
}

func autoConvert_placeholder_CredentialRequestStatus_To_v1alpha1_CredentialRequestStatus(in *placeholder.CredentialRequestStatus, out *CredentialRequestStatus, s conversion.Scope) error {
	out.Credential = (*CredentialRequestCredential)(unsafe.Pointer(in.Credential))
	out.Message = (*string)(unsafe.Pointer(in.Message))
	return nil
}

// Convert_placeholder_CredentialRequestStatus_To_v1alpha1_CredentialRequestStatus is an autogenerated conversion function.
func Convert_placeholder_CredentialRequestStatus_To_v1alpha1_CredentialRequestStatus(in *placeholder.CredentialRequestStatus, out *CredentialRequestStatus, s conversion.Scope) error {
	return autoConvert_placeholder_CredentialRequestStatus_To_v1alpha1_CredentialRequestStatus(in, out, s)
}

func autoConvert_v1alpha1_CredentialRequestTokenCredential_To_placeholder_CredentialRequestTokenCredential(in *CredentialRequestTokenCredential, out *placeholder.CredentialRequestTokenCredential, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_CredentialRequestTokenCredential_To_placeholder_CredentialRequestTokenCredential is an autogenerated conversion function.
func Convert_v1alpha1_CredentialRequestTokenCredential_To_placeholder_CredentialRequestTokenCredential(in *CredentialRequestTokenCredential, out *placeholder.CredentialRequestTokenCredential, s conversion.Scope) error {
	return autoConvert_v1alpha1_CredentialRequestTokenCredential_To_placeholder_CredentialRequestTokenCredential(in, out, s)
}

func autoConvert_placeholder_CredentialRequestTokenCredential_To_v1alpha1_CredentialRequestTokenCredential(in *placeholder.CredentialRequestTokenCredential, out *CredentialRequestTokenCredential, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_placeholder_CredentialRequestTokenCredential_To_v1alpha1_CredentialRequestTokenCredential is an autogenerated conversion function.
func Convert_placeholder_CredentialRequestTokenCredential_To_v1alpha1_CredentialRequestTokenCredential(in *placeholder.CredentialRequestTokenCredential, out *CredentialRequestTokenCredential, s conversion.Scope) error {
	return autoConvert_placeholder_CredentialRequestTokenCredential_To_v1alpha1_CredentialRequestTokenCredential(in, out, s)
}
