/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CredentialRequestListerExpansion allows custom methods to be added to
// CredentialRequestLister.
type CredentialRequestListerExpansion interface{}
