/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// LoginRequestListerExpansion allows custom methods to be added to
// LoginRequestLister.
type LoginRequestListerExpansion interface{}
